### ISSUE TITLE
this error when starting the miner

### ISSUE THREAD

**Issue by DimaKorgenok2** [Cell-chain/wiki#10]
Thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` va2)', miner/src/params.rs:35

![2022-01-25_23-41-51](https://user-images.githubusercontent.com/98428619/151062102-3feb7d40-c9b3-4106-9b65-06b8b7aaf055.png)

**Comment by DimaKorgenok2** [comment]
> Thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` va2)', miner/src/params.rs:35
> 
> ![2022-01-25_23-41-51](https://user-images.githubusercontent.com/98428619/151062102-3feb7d40-c9b3-4106-9b65-06b8b7aaf055.png)

**Comment by DimaKorgenok2** [comment]
CELL
