### ISSUE TITLE
Thread 'main' panicked at 'static values are valid; qed: InvalidFormat'

### ISSUE THREAD

**Issue by DShaurin** [Cell-chain/wiki#16]
cell          | 2022-02-14 19:56:12 Cell Node
cell          | 2022-02-14 19:56:12 ✌️  version 0.4.0-f8889ab-x86_64-linux-gnu
cell          | 2022-02-14 19:56:12 ❤️  by Celllab <https://github.com/cell-chain>, 2021-2022
cell          | 2022-02-14 19:56:12 📋 Chain specification: Cell Testnet
cell          | 2022-02-14 19:56:12 🏷 Node name: six-impulse-7678
cell          | 2022-02-14 19:56:12 👤 Role: FULL
cell          | 2022-02-14 19:56:12 💾 Database: RocksDb at /root/.local/share/cell/chains/cell_testnet/db
cell          | 2022-02-14 19:56:12 ⛓  Native runtime: cell_testnet-101 (cell_testnet-1.tx1.au1)
cell          | 2022-02-14 19:56:12 🏷 Local node identity is: 12D3UuZRvJVhwMKocbXenPMZjJaDCWCcPjn1kSoKwjaypXbcRRhK
cell          | 2022-02-14 19:56:12 📦 Highest known block at #0
cell          | 2022-02-14 19:56:12 〽️ Prometheus server started at 127.0.0.1:9615
cell          | 2022-02-14 19:56:12 Listening for new connections on 127.0.0.1:9944.
cell          |
cell          | ====================
cell          |
cell          | Version: 0.4.0-f8889ab-x86_64-linux-gnu
cell          |
cell          |    0: sp_panic_handler::set::{{closure}}
cell          |    1: std::panicking::rust_panic_with_hook
cell          |              at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:626:17
cell          |    2: std::panicking::begin_panic_handler::{{closure}}
cell          |              at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:519:13
cell          |    3: std::sys_common::backtrace::__rust_end_short_backtrace
cell          |              at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:141:18
cell          |    4: rust_begin_unwind
cell          |              at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:515:5
cell          |    5: core::panicking::panic_fmt
cell          |              at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/panicking.rs:92:14
cell          |    6: core::result::unwrap_failed
cell          |              at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/result.rs:1599:5
cell          |    7: miner::start_miner
cell          |    8: cell::service::new_full
cell          |    9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
cell          |   10: tokio::runtime::enter::Enter::block_on
cell          |   11: tokio::runtime::context::enter
cell          |   12: sc_cli::runner::Runner<C>::run_node_until_exit
cell          |   13: cell::main
cell          |   14: std::sys_common::backtrace::__rust_begin_short_backtrace
cell          |   15: std::rt::lang_start::{{closure}}
cell          |   16: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
cell          |              at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/ops/function.rs:259:13
cell          |       std::panicking::try::do_call
cell          |              at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:401:40
cell          |       std::panicking::try
cell          |              at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:365:19
cell          |       std::panic::catch_unwind
cell          |              at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panic.rs:434:14
cell          |       std::rt::lang_start_internal::{{closure}}
cell          |              at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/rt.rs:45:48
cell          |       std::panicking::try::do_call
cell          |              at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:401:40
cell          |       std::panicking::try
cell          |              at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:365:19
cell          |       std::panic::catch_unwind
cell          |              at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panic.rs:434:14
cell          |       std::rt::lang_start_internal
cell          |              at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/rt.rs:45:20
cell          |   17: main
cell          |   18: __libc_start_main
cell          |   19: _start
cell          |
cell          |
cell          | Thread 'main' panicked at 'static values are valid; qed: InvalidFormat', /home/abm/carbon/node/miner/src/lib.rs:227
cell          |
cell          | This is a bug. Please report it at:
cell          |
cell          |         https://github.com/Cell-chain/wiki.git
cell          |
cell exited with code 1

**Comment by DShaurin** [comment]
This happens if secret phrase is wrong in cmd
